version: '2'
volumes:
  postgres-data: {}
  shuttle-data: {}
services:
  shuttle46:
    image: konvergence/shuttle:latest
    environment:
      DB_HOST: postgres95
      DB_PORT: '5432'
      DB_SHUTTLE_PASSWORD: password
      DB_SHUTTLE_REPO: SHUT_REPO
      DB_SHUTTLE_USER: shuttle
      DB_SYSTEM_PASSWORD: mysecretpassword
      DB_SYSTEM_USER: postgres
      DB_TYPE: postgres
      EXTERNAL_URL_PORT: '443'
      EXTERNAL_URL_PROTOCOL: https
      EXTERNAL_URL_SERVER: demo.shuttle-cloud.com
      LICENSEKEY: 'KEY=changeit'
      WEBAPP_NAME: Shuttles
    stdin_open: true
    volumes:
    - shuttle-data:/data
    tty: true
    command:
    - --run
    labels:
      io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=$${stack_name}/postgres95
  postgres95:
    image: postgres:9.5
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    stdin_open: true
    volumes:
    - postgres-data:/var/lib/postgresql/data
    tty: true
